### ISSUE TITLE
Duplicate definitions

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#116]
ERROR	duplicate_definition	WBPhenotype:0001638	IAO:0000115	Animals are deficient in the formation or disassembly of lysosomes.	
ERROR	duplicate_definition	WBPhenotype:0001784	IAO:0000115	Animals are deficient in the formation or disassembly of lysosomes.	
ERROR	duplicate_definition	WBPhenotype:0000991	IAO:0000115	Activity of the neuron varies from that observed for control animals or neurons. In C. elegans neuron activity is often assayed by observing calcium spikes.	
ERROR	duplicate_definition	WBPhenotype:0001818	IAO:0000115	Activity of the neuron varies from that observed for control animals or neurons. In C. elegans neuron activity is often assayed by observing calcium spikes.

**Comment by chris-grove** [comment]
@matentzn 
I think I've fixed these in the recent build. Closing.
