### ISSUE TITLE
quality part_of anatomical entity

### ISSUE THREAD

**Issue by balhoff** [obophenotype/c-elegans-phenotype-ontology#170]
The logical definition for ['P0 spindle position defective early emb'](http://purl.obolibrary.org/obo/WBPhenotype_0001105) is:

```
'has part' some 
    (position
     and ('part of' some P0)
     and (BFO_0000070 some spindle))
```

This is stating that the PATO quality position is 'part of' a physical structure P0. This causes issues in GO Noctua where we have some mappings that connect P0 up to 'independent continuant', causing the quality to be inferred to be both a 'specifically dependent continuant' and an 'independent continuant' (via the part_of). Can this relation be changed to 'inheres in' or 'inheres in part of'?

**Comment by matentzn** [comment]
While we are at it, can we come up with a pattern for that? Why is this not:

https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormalPositionOfAnatomicalEntityInLocation.yaml

Is this something different?

**Comment by chris-grove** [comment]
No, sorry, I should have explained. 'P0' (pee-zero) is the single celled, fertilized zygote: the original, totipotent cell that gives rise to all other cells in the worm. It's the first stage of the embryo, and hence earliest in development after fertilization. This 'P0' exists as a type of 'Cell' in the worm anatomy ontology. So 'P0' would be an anatomy term in the 'Location' slot of the pattern and the 'mitotic spindle' GO term would be in the 'AnatomicalEntity' slot.

As an aside I ran the ODK pipeline today at about 5pm US ET and again at about 8pm US ET and both times the build failed with:
```        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)^M
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)^M
make: *** [Makefile:229: imports/chebi_import.owl] Error 1^M
rm imports/chebi_terms_combined.txt imports/wbbt_terms_combined.txt imports/ro_terms_combined.txt imports/go_terms_combined.txt imports/wbls_terms_combined.txt^M
Thu Oct 21 20:57:09 EDT 2021
```

I'll try it again tomorrow.
