### ISSUE TITLE
Release tag different than release date (2023-07-10 vs 2023-07-12)

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/c-elegans-phenotype-ontology#192]
I noticed in the OBO Dashboard that the version IRI is not resolving. I checked the releases here and found out the dates are different. The tag should be 2023-07-10 instead of 2023-07-12.

![Screenshot 2023-09-29 at 15 02 40](https://github.com/obophenotype/c-elegans-phenotype-ontology/assets/2208124/695a4f52-5e23-4402-943f-813f1d36dd41)

**Comment by chris-grove** [comment]
@anitacaron Thanks for catching this and letting me know!
@matentzn I think what happened here is a ran the ODK pipeline on July 10th and then officially made the release in GitHub on July 12th. It sounds like when I make the dated version release tag it needs to match the date on which I ran the ODK pipeline? Can you confirm?

**Comment by matentzn** [comment]
yes, the ontology version MUST match with the date the ontology was created! Thanks for checking and thanks @anitacaron for reporting!

**Comment by chris-grove** [comment]
@anitacaron @matentzn 
OK, I think I've addressed the issue. Can either of you confirm?

**Comment by anitacaron** [comment]
The issue is solved!
