### ISSUE TITLE
Obsolete GO term imported as not obsolete, throwing ODK pipeline error

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/c-elegans-phenotype-ontology#193]
@matentzn 

I'm getting an error in my ODK pipeline:

```
2024-01-09 17:50:40,308 ERROR org.obolibrary.robot.ReasonOperation - Only equivalent classes that have been asserted are allowed. Inferred equivalencies are forbidden.^M
2024-01-09 17:50:40,313 ERROR org.obolibrary.robot.ReasonOperation - Equivalence: <http://purl.obolibrary.org/obo/GO_0032989> == <http://purl.obolibrary.org/obo/GO_0032990>^M
make: *** [Makefile:678: wbphenotype-full.owl] Error 1^M
rm imports/bfo_terms_combined.txt imports/go_terms_combined.txt imports/pato_terms_combined.txt imports/iao_terms_combined.txt imports/wbls_terms_combined.txt imports/cl_terms_combined.txt imports/ro_terms_combined.txt imports/wbbt_terms_combined.txt^M
Please remember to update your ODK image from time to time: https://oboacademy.github.io/obook/howto/odk-update/.
Tue Jan  9 12:50:40 EST 2024
```

Some notes: I think part of the issue is that GO:0032990 (“cell part morphogenesis”) is obsolete and has been replaced by GO:0032989 (“cellular component morphogenesis”):
https://amigo.geneontology.org/amigo/term/GO:0032990
https://amigo.geneontology.org/amigo/term/GO:0032989
but the ontology imports are still bringing in GO:0032990 as if it is still a valid term. As for equivalencies I see in Protege (see screenshots), it seems that “cell part morphogenesis” is an asserted subclass of “cellular component morphogenesis”. After running the reasoner (ELK), I don’t see an explicit equivalency of the two terms, but maybe I’m forgetting how to do it properly. The EQ for “cell part morphogenesis” is :
```
'anatomical structure morphogenesis'
 and ('results in morphogenesis of' some 'cellular anatomical entity')
```

and for "cellular component morphogenesis" is:

```
'anatomical structure morphogenesis'
 and ('results in morphogenesis of' some cellular_component)
```

Screenshots:
<img width="738" alt="Screenshot 2024-01-14 at 10 34 28 AM" src="https://github.com/obophenotype/c-elegans-phenotype-ontology/assets/611382/f9960b07-6046-42c3-bae5-da13a2f0e5db">
<img width="659" alt="Screenshot 2024-01-14 at 10 34 16 AM" src="https://github.com/obophenotype/c-elegans-phenotype-ontology/assets/611382/4d1318b4-d90a-4a63-8131-6f13c8a9a9a4">
<img width="530" alt="Screenshot 2024-01-14 at 10 33 56 AM" src="https://github.com/obophenotype/c-elegans-phenotype-ontology/assets/611382/ef141eb0-a8fa-4cd1-8b27-779282ed9ac9">

**Comment by anitacaron** [comment]
Hi @chris-grove, you won't have this issue if you use the base file for each import. The base file only gets the terms from the ontology. As you show in the screenshots, the two GO terms are also present in the CL and PATO imports.

You need to change in the `wbphenotype-odk.yaml`:
```yaml
import_group:
  products: 
    ...
    - id: pato
      use_base: true
    - id: cl
      use_base: true
    - id: iao
    - id: bfo
```

Then `sh run.sh make update_repo` and then update the CL and PATO imports.

Let me know if you need further help.

**Comment by chris-grove** [comment]
@anitacaron 
Thanks! That seems to have done the trick! My ODK pipeline ran successfully and I've commited to the repo. Thanks again!

**Comment by JCGiron** [comment]
I had the same issue releasing [AISM](https://github.com/insect-morphology/aism) and this solution worked!
