### ISSUE TITLE
Trailing whitespace in some definitions

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#2]
Currently hotfixed by removing the requirement from the make file, but should be sorted.

```
#  trailing-whitespace
VCHECKS = equivalent-classes owldef-self-reference xref-syntax nolabels
```

**Comment by matentzn** [comment]
In the end, you might need up to 10GB of docker memory - that is what I used with my 16GB laptop, and it worked fine! The error you send was indeed memory limit related. Here is the list of all 69 annotations that violate the whitespace rules

[trailing-whitspace-violations.txt](https://github.com/obophenotype/c-elegans-phenotype-ontology/files/2607598/trailing-whitspace-violations.txt)

**Comment by chris-grove** [comment]
Fixed with
https://github.com/obophenotype/c-elegans-phenotype-ontology/pull/30
