### ISSUE TITLE
Implement Upheno absent pattern

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#29]
Implement by adding absent.yaml to external.txt in the src/patterns/dosdp-patterns directory.

Implement first instance: 'alae absent' in respective absent.tsv. When you are done, remember to delete from donotedit. Feel free to add as many absent ones as you find.

**Comment by chris-grove** [comment]
<img width="275" alt="screenshot 2018-11-21 15 38 37" src="https://user-images.githubusercontent.com/611382/48867252-94668900-eda3-11e8-80ad-c5cb439fc35c.png">

**Comment by matentzn** [comment]
Make sure you remove the two new classes in absent.tsv and missingProcess.tsv from here: https://github.com/obophenotype/c-elegans-phenotype-ontology/blob/master/src/ontology/wbphenotype-equivalent-axioms-subq.owl

If they are mentioned at all.

**Comment by chris-grove** [comment]
Just added more 'absent' and 'missingProcess' terms as per pull request:

https://github.com/obophenotype/c-elegans-phenotype-ontology/pull/43/commits

More terms will likely be applied in the future, but require additional discussion/consideration.

@matentzn 
Maybe we can close this ticket as the pattern has been implemented?

**Comment by matentzn** [comment]
Yes :) Great one.
