### ISSUE TITLE
There are a bunch of classes in the ontology with no labels

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#3]
Currently hotfixed by removing the requirement from the make file, but should be sorted.

```
#  trailing-whitespace nolabels
VCHECKS = equivalent-classes owldef-self-reference xref-syntax
```

Could this be an artefact of the EQ-definitions file? Maybe some classes were deleted in wb.obo?

**Comment by chris-grove** [comment]
Working on this now

**Comment by matentzn** [comment]
I have added the no-labels check back into the QC pipeline of the Makefile. Lets try it later together.
