### ISSUE TITLE
Fix abnormal phenotypes

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#40]
We need to identify all phenotypes with 'abnormal' in the 'quality' spot and fix them to be ordinary abnormal phenotypes:

- Open Protege, run ELK
- Go to DL query tab, run `'has part' some abnormal`, make sure only the 'subclasses' checkbox is clicked on the right of the DL query results.
- Go to all of them, if they look like [development variant](https://www.ebi.ac.uk/ols/ontologies/wbphenotype/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FWBPhenotype_0000518), i.e. 

```
has part some (
    abnormal and 
    inheres in some developmental process)
```

They should go into the 'abnormal' pattern.

**Comment by chris-grove** [comment]
See 
https://github.com/obophenotype/c-elegans-phenotype-ontology/pull/42

for removal of offending EQ defs from file:

~/src/ontology/wbphenotype-equivalent-axioms-subq.owl

**Comment by matentzn** [comment]
Cool, but a real fix would be to add them back as abnormal.tsv were applicable; but I guess with your documented list that will be easy enough. :P Good one.

**Comment by chris-grove** [comment]
Well, the plan is to eventually add them as appropriate to the 'abnormal' pattern, but it will take some time (this is the first step), and many will not be transferable to the 'abnormal' pattern.

**Comment by chris-grove** [comment]
OK, update: new pull request should address the lowest hanging fruit:

https://github.com/obophenotype/c-elegans-phenotype-ontology/pull/43/commits
