### ISSUE TITLE
Investigate Bus Error of last release attempt

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#57]
https://www.dropbox.com/s/mt8wzqoeuim2ql3/C_eleg_phen_ont_make_prepare_release_output_Feb_28_2019.txt?dl=0

**Comment by chris-grove** [comment]
Moved DropBox file here:
https://www.dropbox.com/s/mt8wzqoeuim2ql3/CPO_ODK_make_prepare_release_output_Feb_28_2019.txt?dl=0

**Comment by chris-grove** [comment]
Here's a DropBox directory of outputs:
https://www.dropbox.com/sh/hhy3ird93ghuwuh/AADKKCkeu3ECiFxv7iUfoMdfa?dl=0

**Comment by matentzn** [comment]
Re-open if turns out a problem again.
