### ISSUE TITLE
Syntax error in Apr 21 2019 release

### ISSUE THREAD

**Issue by althonos** [obophenotype/c-elegans-phenotype-ontology#77]
Hi there!

The latest release of `wbphenotype` has an issue in its OBO file: on line 37520, the definition of the `WBPhenotype:0002510` term somehow got exported as a `namespace` instead (thus causing a syntax error):

```ini
[Term]
id: WBPhenotype:0002509
name: extra dopaminergic neuron
def: "Animals produce an excess number of dopaminergic neurons compared to controls." [WB:WBPaper00053165, WB:WBPerson2987, WB:WBPerson3252]
is_a: WBPhenotype:0002508 ! extra neuron

[Term]
id: WBPhenotype:0002510
name: fewer neurons
namespace: Animals exhibit fewer neurons compared to control animals. {xref="WB:WBPerson3252", xref="WB:WBPerson2987", xref="WB:WBPaper00053165"}
is_a: WBPhenotype:0002174 ! cell number decreased
```

For the record, the previous release (WS271) didn't have that issue.

**Comment by chris-grove** [comment]
@althonos 
Hi there, thanks for pointing this out! I had noticed this and thought that I fixed it in the current release. I will fix it now.

**Comment by chris-grove** [comment]
@althonos 
OK, I've rebuilt and created a new release with today's date. Please let me know if you encounter any other issues. Thanks again!
